version: '3.5'

services:
  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    networks:
      - nt-rinha
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096 -c synchronous_commit=0 -c fsync=0 -c full_page_writes=0 -c max_connections=400
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '1.0GB'

  api01: 
    container_name: container-app1
    image: img-api01
    build: 
      context: .
    hostname: api01
    depends_on:
      - db
    networks:
      - nt-rinha
    environment:
      - NATS_URL=nats:4222
      - DB_CONNECTION_STRING=Host=db;Username=admin;Password=123;Database=rinha;Connection Pruning Interval=10;Connection Idle Lifetime=300;
      - ASPNETCORE_URLS=http://*:80
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "0.75GB"

  api02: 
    container_name: container-app2
    image: img-api02
    build: 
      context: .
    hostname: api02
    depends_on:
      - db
    networks:
      - nt-rinha
    environment:
      - NATS_URL=nats:4222
      - DB_CONNECTION_STRING=Host=db;Username=admin;Password=123;Database=rinha;Connection Pruning Interval=10;Connection Idle Lifetime=300;
      - ASPNETCORE_URLS=http://*:80
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "0.75GB"
  nginx:
    image: docker.io/nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    command: ["nginx", "-g", "daemon off;"]
    networks:
      - nt-rinha
    ulimits:
      nproc: 1000000
      nofile:
        soft: 1000000
        hard: 1000000
    ports:
      - "9999:9999"  
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '0.5GB'
networks:   
  nt-rinha:
    driver: bridge
      