version: '3'

services:
  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    networks:
      - nt-teste
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096 -c synchronous_commit=0 -c fsync=0 -c full_page_writes=0
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.4GB'

  api01: &api
    image: rinha-api01
    build: 
      context: .
      # dockerfile: web.Dockerfile
    hostname: rinha-api01
    depends_on:
      - db
    ports:
      - "5002:80"
    networks:
      - nt-teste
    # environment:
    #   - ASPNETCORE_URLS=http://localhost:80
    # expose:
    #   - "80"
    deploy:
      resources:
        limits:
          cpus: "0.568"
          memory: "1.0GB"
networks:   
  nt-teste:
    driver: bridge
      